[package]
name = "kstore"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

byteorder = "1.4.3"
crc = "3.0.1"
serde = "1.0.181"
serde_derive = "1.0.181"

[lib]
name = "kstore"
path = "src/lib.rs"
